const products=[
{id:1,brand:"Nova",name:"Nova X1 Pro 5G",category:"Phones",price:74999,old:84999,rating:4.8,reviews:324,art:"📱",color:"Midnight",spec:{Display:"6.7” AMOLED 120Hz",Processor:"X1 Ultra • 3.4GHz",RAM:"12 GB",Storage:"256 GB",Battery:"5,000 mAh",Camera:"50 MP + 12 MP",Warranty:"1 Year"},desc:"A flagship 5G smartphone built for creators and power users, with a smooth AMOLED display and all-day battery."},
{id:2,brand:"Orbit",name:"OrbitBook Air 14",category:"Laptops",price:89990,old:99990,rating:4.7,reviews:218,art:"💻",color:"Silver",spec:{Display:"14” 2.8K OLED",Processor:"Core Ultra 7",RAM:"16 GB",Storage:"512 GB SSD",Battery:"18 hours",Weight:"1.22 kg",Warranty:"1 Year"},desc:"A feather-light OLED laptop for work, study and creative workflows, tuned for quiet all-day performance."},
{id:3,brand:"Pulse",name:"Pulse Buds Pro ANC",category:"Audio",price:8999,old:11999,rating:4.6,reviews:581,art:"🎧",color:"Graphite",spec:{Driver:"11mm Dynamic",ANC:"Adaptive ANC",Battery:"38 hours",Codec:"AAC / LDAC",Water:"IPX5",Mic:"6-mic AI",Warranty:"1 Year"},desc:"Immersive wireless audio with adaptive noise cancellation, low-latency mode and a pocket-size charging case."},
{id:4,brand:"Zenith",name:"Zenith Watch S",category:"Wearables",price:14999,old:17999,rating:4.5,reviews:142,art:"⌚",color:"Black",spec:{Display:"1.8” AMOLED",GPS:"Dual-band",Battery:"14 days",Health:"HR / SpO₂ / Sleep",Water:"5 ATM",Calls:"Bluetooth",Warranty:"1 Year"},desc:"A premium smartwatch that balances health insights, GPS accuracy and a clean AMOLED interface."},
{id:5,brand:"Vertex",name:"Vertex PlayStation Pad X",category:"Gaming",price:6999,old:7999,rating:4.7,reviews:97,art:"🎮",color:"White",spec:{Connection:"Wireless + USB-C",Battery:"30 hours",Haptics:"HD haptics",Triggers:"Adaptive",Audio:"3.5mm jack",Weight:"280 g",Warranty:"1 Year"},desc:"Responsive wireless gaming controller with adaptive triggers, precise haptics and comfortable ergonomics."},
{id:6,brand:"Nova",name:"Nova Tab 12",category:"Phones",price:32999,old:36999,rating:4.6,reviews:185,art:"📟",color:"Blue",spec:{Display:"12.1” 120Hz",Processor:"X2 Octa-core",RAM:"8 GB",Storage:"256 GB",Battery:"9,000 mAh",Camera:"13 MP",Warranty:"1 Year"},desc:"A versatile large-screen tablet for entertainment, notes and creative work."},
{id:7,brand:"Orbit",name:"OrbitBook Studio 16",category:"Laptops",price:124990,old:139990,rating:4.9,reviews:76,art:"🖥️",color:"Space Gray",spec:{Display:"16” 3.2K OLED",Processor:"Core Ultra 9",RAM:"32 GB",Storage:"1 TB SSD",GPU:"RTX 5060",Weight:"1.8 kg",Warranty:"2 Years"},desc:"A creator-focused performance laptop with a color-rich OLED display and dedicated graphics."},
{id:8,brand:"Pulse",name:"Pulse Max Speaker",category:"Audio",price:12999,old:15999,rating:4.4,reviews:203,art:"🔊",color:"Black",spec:{Output:"60 W",Battery:"24 hours",Bluetooth:"5.4",Water:"IP67",Stereo:"True Wireless",Modes:"Party / Bass",Warranty:"1 Year"},desc:"Room-filling wireless sound with deep bass, rugged water resistance and long battery life."}
];
let cart=JSON.parse(localStorage.getItem("tw_cart")||"[]");
let compare=JSON.parse(localStorage.getItem("tw_compare")||"[]");
let saved=JSON.parse(localStorage.getItem("tw_saved")||"[]");
let currentProduct=1;
let onboardingPage=0;

function money(n){return "₹"+n.toLocaleString("en-IN")}
function getProduct(id){return products.find(p=>p.id===id)}
function saveState(){localStorage.setItem("tw_cart",JSON.stringify(cart));localStorage.setItem("tw_compare",JSON.stringify(compare));localStorage.setItem("tw_saved",JSON.stringify(saved));updateBadges()}
function updateBadges(){document.getElementById("cartBadge").textContent=cart.reduce((s,x)=>s+x.qty,0);document.getElementById("compareBadge").textContent=compare.length}
function showToast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
function skipOnboarding(){localStorage.setItem("tw_seen","1");document.getElementById("onboarding").classList.remove("active");document.getElementById("app").classList.remove("hidden");showScreen("home")}
function nextOnboarding(){if(onboardingPage<2){onboardingPage++;document.querySelectorAll(".dot").forEach((d,i)=>d.classList.toggle("active",i===onboardingPage));document.querySelector(".onboard-copy h1").innerHTML=onboardingPage===1?"Compare smarter.<br><em>Buy better.</em>":"Everything you need<br><em>in one place.</em>";document.querySelector(".onboard-copy p").textContent=onboardingPage===1?"Put products side by side, spot spec differences, read real reviews and choose with confidence.":"Save favorites, track price drops and manage every order from one simple account."; }else skipOnboarding()}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));const s=document.getElementById(id);if(s)s.classList.add("active");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));if(id==="home")renderFeatured();if(id==="products")applyFilters();if(id==="cart")renderCart();if(id==="compare")renderCompare();if(id==="profile")renderProfile();if(id==="checkout")renderCheckout();window.scrollTo({top:0,behavior:"smooth"})}
function card(p){return `<article class="product-card"><div class="product-image"><button class="heart ${saved.includes(p.id)?"saved":""}" onclick="event.stopPropagation();toggleSave(${p.id})">${saved.includes(p.id)?"♥":"♡"}</button><div class="art">${p.art}</div></div><div class="product-info" onclick="openDetail(${p.id})"><span class="brand-name">${p.brand}</span><div class="product-name">${p.name}</div><div class="rating">★ ${p.rating} <span>(${p.reviews})</span></div><div class="price-row"><div><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span></div><button class="mini-add" onclick="event.stopPropagation();addCart(${p.id})">+</button></div></div></article>`}
function renderFeatured(){document.getElementById("featuredGrid").innerHTML=products.slice(0,4).map(card).join("")}
function renderProducts(list=products){document.getElementById("productGrid").innerHTML=list.length?list.map(card).join(""):`<div class="empty" style="grid-column:1/-1"><div class="emoji">🔎</div><h3>No products found</h3><p class="small-note">Try another keyword or clear your filters.</p></div>`;document.getElementById("resultText").textContent=`Showing ${list.length} product${list.length===1?"":"s"}`}
function applyFilters(){let q=(document.getElementById("globalSearch")?.value||"").toLowerCase(),cat=document.getElementById("categoryFilter").value,brand=document.getElementById("brandFilter").value,sort=document.getElementById("sortFilter").value;let list=products.filter(p=>(!q||(p.name+" "+p.brand+" "+p.category).toLowerCase().includes(q))&&(cat==="All"||p.category===cat)&&(brand==="All"||p.brand===brand));if(sort==="priceLow")list.sort((a,b)=>a.price-b.price);if(sort==="priceHigh")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);renderProducts(list)}
function handleSearch(v){if(document.getElementById("products").classList.contains("active"))applyFilters();else if(v.trim()){showScreen("products");applyFilters()}}
function toggleFilters(){document.getElementById("filterPanel").classList.toggle("hidden")}
function filterCategory(c){showScreen("products");document.getElementById("categoryFilter").value=c;applyFilters()}
function openDetail(id){currentProduct=id;const p=getProduct(id);document.getElementById("detailContent").innerHTML=`<div class="detail-grid"><div class="detail-visual"><div class="art">${p.art}</div><button class="heart ${saved.includes(p.id)?"saved":""}" onclick="toggleSave(${p.id})">${saved.includes(p.id)?"♥":"♡"}</button></div><div class="detail-info"><span class="eyebrow blue">${p.brand} • ${p.category.toUpperCase()}</span><h1>${p.name}</h1><div class="rating">★ ${p.rating} <span>Based on ${p.reviews} reviews</span></div><p class="desc">${p.desc}</p><div class="detail-price">${money(p.price)} <span class="old-price">${money(p.old)}</span></div><div class="compare-box">⇄ <b>Compare specs</b><span> Add this product to side-by-side comparison.</span></div><div class="specs">${Object.entries(p.spec).map(([k,v])=>`<div><b>${k}</b></div><div>${v}</div>`).join("")}</div><div class="detail-actions"><button class="btn primary" onclick="addCart(${p.id})">Add to cart</button><button class="btn outline" onclick="toggleCompare(${p.id})">${compare.includes(p.id)?"✓ Added to compare":"⇄ Compare"}</button><button class="btn outline" onclick="showScreen('reviews');renderReviews()">★ Reviews</button></div></div></div>`;showScreen("detail")}
function toggleSave(id){saved.includes(id)?saved=saved.filter(x=>x!==id):saved.push(id);saveState();showToast(saved.includes(id)?"Saved to your wishlist":"Removed from wishlist");if(document.getElementById("detail").classList.contains("active"))openDetail(id);else renderFeatured();if(document.getElementById("products").classList.contains("active"))applyFilters()}
function toggleCompare(id){if(compare.includes(id)){compare=compare.filter(x=>x!==id);showToast("Removed from comparison")}else if(compare.length>=3){showToast("Compare up to 3 products")}else{compare.push(id);showToast("Added to comparison")}saveState();openDetail(id)}
function clearCompare(){compare=[];saveState();renderCompare()}
function renderCompare(){const ps=compare.map(getProduct);if(!ps.length){document.getElementById("compareContent").innerHTML=`<div class="empty"><div class="emoji">⇄</div><h2>Your comparison is empty</h2><p class="small-note">Add up to 3 products to compare specifications side by side.</p><button class="btn primary" onclick="showScreen('products')">Browse products</button></div>`;return}let keys=[...new Set(ps.flatMap(p=>Object.keys(p.spec)))];document.getElementById("compareContent").innerHTML=`<div class="compare-table"><table><thead><tr><th>Specification</th>${ps.map(p=>`<th class="compare-product"><div class="art">${p.art}</div><b>${p.name}</b><div class="rating">★ ${p.rating}</div><strong>${money(p.price)}</strong></th>`).join("")}</tr></thead><tbody>${keys.map(k=>{let vals=ps.map(p=>p.spec[k]||"—"),diff=new Set(vals).size>1;return `<tr><th>${k}</th>${vals.map(v=>`<td class="${diff?"diff":""}">${v}</td>`).join("")}</tr>`}).join("")}</tbody></table></div><p class="small-note" style="margin-top:12px">Highlighted cells indicate a specification difference.</p>`}
function addCart(id){const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});saveState();showToast("Added to cart");}
function removeCart(id){cart=cart.filter(x=>x.id!==id);saveState();renderCart()}
function changeQty(id,d){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<=0)removeCart(id);else{saveState();renderCart()}}
function totals(){let subtotal=cart.reduce((s,x)=>{let p=getProduct(x.id);return s+p.price*x.qty},0);let shipping=subtotal>=50000||subtotal===0?0:199;let discount=subtotal>=100000?5000:subtotal>=50000?2500:0;return{subtotal,shipping,discount,total:subtotal+shipping-discount}}
function summaryHTML(){let t=totals();return `<h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><b>${money(t.subtotal)}</b></div><div class="summary-row"><span>Shipping</span><b>${t.shipping?"₹"+t.shipping:"FREE"}</b></div><div class="summary-row"><span>Member savings</span><b style="color:var(--green)">-${money(t.discount)}</b></div><div class="summary-row total"><span>Total</span><b>${money(t.total)}</b></div>`}
function renderCart(){let el=document.getElementById("cartContent");document.getElementById("cartSubtitle").textContent=`${cart.reduce((s,x)=>s+x.qty,0)} item${cart.reduce((s,x)=>s+x.qty,0)===1?"":"s"}`;if(!cart.length){el.innerHTML=`<div class="empty"><div class="emoji">🛒</div><h2>Your cart is waiting</h2><p class="small-note">Add something awesome and it will show up here.</p><button class="btn primary" onclick="showScreen('products')">Start shopping</button></div>`;return}el.innerHTML=`<div class="cart-layout"><div>${cart.map(x=>{let p=getProduct(x.id);return `<div class="cart-item"><div class="cart-img">${p.art}</div><div><span class="brand-name">${p.brand}</span><h3 style="margin:5px 0">${p.name}</h3><div class="price">${money(p.price)}</div></div><div class="cart-side"><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${p.id},1)">+</button></div><button class="text-btn" style="color:#D32F2F;padding:7px 0" onclick="removeCart(${p.id})">Remove</button></div></div>`}).join("")}</div><aside class="summary-card">${summaryHTML()}<button class="btn primary full" onclick="showScreen('checkout')">Proceed to checkout →</button><p class="small-note" style="text-align:center;margin-top:12px">🔒 Secure checkout • Free returns</p></aside></div>`}
function renderCheckout(){document.getElementById("checkoutSummary").innerHTML=summaryHTML()+`<hr style="border:0;border-top:1px solid var(--line)"><div class="small-note">Your order is protected by TechWorld Buyer Guarantee.</div>`}
function placeOrder(e){e.preventDefault();if(!cart.length){showToast("Your cart is empty");return}const code="TW-"+new Date().getFullYear()+"-"+String(Math.floor(1000+Math.random()*9000));document.getElementById("orderCode").textContent=code;document.getElementById("confirmationText").textContent=`We've received your order of ${cart.reduce((s,x)=>s+x.qty,0)} item(s). A confirmation will be sent to your email.`;cart=[];saveState();showScreen("confirmation");}
function renderReviews(){let p=getProduct(currentProduct);let names=["Aarav K.","Meera S.","Rohan P.","Ishita M."];let texts=["The specs are exactly as listed and the performance feels premium. Delivery was quick too.","Really happy with the build quality. The setup was straightforward and the experience feels polished.","Great value during the sale. Battery and display are the highlights for me.","Customer support answered my question before I ordered. Would buy again."];document.getElementById("reviewsContent").innerHTML=`<span class="eyebrow blue">CUSTOMER VOICE</span><h1 style="font:700 32px Poppins">${p.name} reviews</h1><div class="review-summary"><div class="score-card"><div class="big-score">${p.rating}</div><div class="rating">★★★★★</div><p class="small-note">${p.reviews} verified ratings</p></div><div class="bars">${[5,4,3,2,1].map((n,i)=>`<div><b>${n}</b><div class="bar"><i style="width:${[82,12,4,1,1][i]}%"></i></div><span>${[82,12,4,1,1][i]}%</span></div>`).join("")}</div></div><div class="review-list">${names.map((n,i)=>`<div class="review"><div class="review-head"><b>${n}</b><span class="rating">★★★★★</span></div><small class="small-note">Verified purchase • ${i+1} week${i?"s":""} ago</small><p>${texts[i]}</p><button class="text-btn" onclick="showToast('Thanks! Helpful vote recorded.')">♡ Helpful</button></div>`).join("")}</div>`}
function renderProfile(){profileTab("orders",document.querySelector(".profile-tabs button"))}
function profileTab(tab,btn){document.querySelectorAll(".profile-tabs button").forEach(b=>b.classList.remove("active"));if(btn)btn.classList.add("active");let el=document.getElementById("profilePanel");if(tab==="orders")el.innerHTML=`<div class="order-card"><div><b>TW-2026-1842</b><p class="small-note">Nova X1 Pro 5G • 1 item • ₹74,999</p></div><span class="order-status">Delivered</span></div><div class="order-card"><div><b>TW-2026-1618</b><p class="small-note">Pulse Buds Pro ANC • 2 items • ₹17,998</p></div><span class="order-status">Delivered</span></div>`;if(tab==="saved")el.innerHTML=saved.length?`<div class="product-grid">${saved.map(id=>getProduct(id)).filter(Boolean).map(card).join("")}</div>`:`<div class="empty"><div class="emoji">♡</div><h2>No saved products</h2><p class="small-note">Tap the heart on any product to save it for later.</p></div>`;if(tab==="settings")el.innerHTML=`<div class="form-card"><h2>Preferences</h2><div class="order-card"><div><b>Price drop alerts</b><p class="small-note">Get notified when saved products become cheaper.</p></div><input type="checkbox" checked style="width:auto"></div><div class="order-card"><div><b>Deal notifications</b><p class="small-note">Weekly highlights and new arrivals.</p></div><input type="checkbox" checked style="width:auto"></div><button class="btn outline" onclick="showToast('Preferences saved')">Save changes</button></div>`}
function login(e){if(e)e.preventDefault();showToast("Signed in successfully");setTimeout(()=>showScreen("home"),500)}
function init(){updateBadges();renderFeatured();renderProducts();if(localStorage.getItem("tw_seen")){document.getElementById("onboarding").classList.remove("active");document.getElementById("app").classList.remove("hidden");showScreen("home")}else{document.getElementById("onboarding").classList.add("active")}}
init();
